eureka:
  client:
    service-url:
      defaultZone: http://eureka-docker:8501/eureka/
#虽然这个配置没有提示但是有用。使用OkHttp替换默认的url请求
#feign:
#  httpclient:
#    enabled: true
#    connection-timeout: 5000
#zuul:
#  routes:
#    saber-auth:
#      path: /saber-auth/**
#      service-id: saber-auth-provider