version: '3'
services:
  eureka-docker:
    image: 119.23.29.13/saber/saber-eureka:latest
    ports:
      - '8501:8501'
    volumes:
      - '/www/logs:/www/logs'
  saber-auth:
    image: 119.23.29.13/saber/saber-authr-service:latest
    depends_on:
      - eureka-docker
    volumes:
      - '/www/logs:/www/logs'
  zuul:
    image: 119.23.29.13/saber/saber-zuul:latest
    depends_on:
      - saber-auth
    ports:
      - '8070:8080'
    volumes:
      - '/www/logs:/www/logs'