server:
  port: 8100
spring:
  application:
    name: saber-test
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8501/eureka/




