spring:
  application:
    name: saber-eureka
server:
  port: 8502
eureka:
  instance:
    hostname: peer2
    home-page-url: http://${eureka.hostname}:${server.port}
  client:
    service-url:
      defaultZone: http://peer1:8501/eureka/, http://peer3:8503/eureka/
  server:
    renewal-percent-threshold: 0.49
