server:
  port: 8501
spring:
  application:
    name: saber-auth
  datasource:
    url: jdbc:mysql://localhost:3306/saber_auth?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234
    druid:
      filters: wall
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
logging:
  level:
    fgo.saber.auth.provider.dao: debug
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: true



