server:
  port: 8502
spring:
  application:
    name: saber-auth-controller
  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        register: false
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8