server:
  port: 8602
spring:
  application:
    name: saber-auth-controller
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    fgo.saber.auth.api.cloudservice: debug
#虽然这个配置没有提示但是有用。使用OkHttp替换默认的url请求
feign:
  name: saber-auth-provider
  okhttp:
    enabled: true
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8501/eureka/