server:
  port: 8502
spring:
  application:
    name: saber-auth-controller
  cloud:
    consul:
      port: 8500
      host: 127.0.0.1
      discovery:
        register: true
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
logging:
  level:
    fgo.saber.auth.api.cloudservice: debug
#虽然这个配置没有提示但是有用。使用OkHttp替换默认的url请求
feign:
  name: saber-auth-provider
  okhttp:
    enabled: true