server:
  port: 8601
spring:
  application:
    name: saber-auth-provider
  datasource:
    url: jdbc:mysql://192.168.187.201:3306/saber_authr?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    druid:
      filters: wall
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  main:
    allow-bean-definition-overriding: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
logging:
  level:
    fgo.saber.authr.service.dao: debug
mapper:
  mappers: tk.mybatis.mapper.common.Mapper
  not-empty: true
eureka:
  client:
    service-url:
     defaultZone: http://localhost:8501/eureka/




