
spring:
  datasource:
    url: jdbc:mysql://saber-mysql:3306/saber_authr?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    druid:
      filters: wall
eureka:
  client:
    service-url:
     defaultZone: http://eureka-docker:8501/eureka/




